[{"type":"message","ts":"1541371465.001700","attachments":[{"fallback":"\n\npatch 8.1.0511: ml_get error when calling a function with a range\n\nProblem:    ml_get error when calling a function with a range.\nSolution:   Don't position the cursor after the last line.\n","title":"patch 8.1.0511: ml_get error when calling a function with a range","title_link":"https://github.com/vim/vim/commit/9e353b5265bd7fa103caf4e5a9b3c99f344f548e","text":"\n\npatch 8.1.0511: ml_get error when calling a function with a range\n\nProblem:    ml_get error when calling a function with a range.\nSolution:   Don't position the cursor after the last line.\n","thumb_url":"https://ifttt.com/images/no_image_card.png","mrkdwn_in":["text","pretext"],"blocks":null,"thumb_width":800,"thumb_height":494}],"subtype":"bot_message","bot_id":"B0VCFSN5C","username":"IFTTT","icons":{"image_48":"https://a.slack-edge.com/8f51/img/services/ifttt_48.png"},"replace_original":false,"delete_original":false,"blocks":null}]
