[{"type":"message","text":"<https://github.com/vim/vim/commit/c620c055ce8505596a7208ba696a32b8a3be4f4b|patch 8.2.1154: Vim9: crash when using imported function>\npatch 8.2.1154: Vim9: crash when using imported function\n\nProblem:    Vim9: crash when using imported function.\nSolution:   Check for a function type.  Set the script context when calling a\n            function. (closes #6412)","ts":"1594215492.148500","attachments":[{"fallback":"GitHub: patch 8.2.1154: Vim9: crash when using imported function · vim/vim@c620c05","id":1,"title":"patch 8.2.1154: Vim9: crash when using imported function · vim/vim@c620c05","title_link":"https://github.com/vim/vim/commit/c620c055ce8505596a7208ba696a32b8a3be4f4b","text":"Problem: Vim9: crash when using imported function. Solution: Check for a function type. Set the script context when calling a function. (closes #6412)","thumb_url":"https://avatars0.githubusercontent.com/u/11618545?s=400&v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/c620c055ce8505596a7208ba696a32b8a3be4f4b","original_url":"https://github.com/vim/vim/commit/c620c055ce8505596a7208ba696a32b8a3be4f4b"}],"edited":{"user":"BPV6T0C1J","ts":"1594215493.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"<https://github.com/vim/vim/commit/bb790dcc46b74e6f9a1c4126be8a575f9fe73444|patch 8.2.1150: ml_get error when using Python>\npatch 8.2.1150: ml_get error when using Python\n\nProblem:    ml_get error when using Python. (Yegappan Lakshmanan)\nSolution:   Check the line number is not out of range.  Call \"Check\" with\n            \"fromObj\" instead of \"from\".","ts":"1594145894.147700","attachments":[{"fallback":"GitHub: patch 8.2.1150: ml_get error when using Python · vim/vim@bb790dc","id":1,"title":"patch 8.2.1150: ml_get error when using Python · vim/vim@bb790dc","title_link":"https://github.com/vim/vim/commit/bb790dcc46b74e6f9a1c4126be8a575f9fe73444","text":"Problem: ml_get error when using Python. (Yegappan Lakshmanan) Solution: Check the line number is not out of range. Call &amp;quot;Check&amp;quot; with &amp;quot;fromObj&amp;quot; instead of &amp;quo...","thumb_url":"https://avatars0.githubusercontent.com/u/11618545?s=400&v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/bb790dcc46b74e6f9a1c4126be8a575f9fe73444","original_url":"https://github.com/vim/vim/commit/bb790dcc46b74e6f9a1c4126be8a575f9fe73444"}],"edited":{"user":"BPV6T0C1J","ts":"1594145894.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"<https://github.com/vim/vim/commit/0ab55d62012c1fb38c4b540a4233421820a59389|patch 8.2.1151: insufficient test coverage for Python>\npatch 8.2.1151: insufficient test coverage for Python\n\nProblem:    Insufficient test coverage for Python.\nSolution:   Add more test cases. (Yegappan Lakshmanan, closes #6415)","ts":"1594149494.147900","attachments":[{"fallback":"GitHub: patch 8.2.1151: insufficient test coverage for Python · vim/vim@0ab55d6","id":1,"title":"patch 8.2.1151: insufficient test coverage for Python · vim/vim@0ab55d6","title_link":"https://github.com/vim/vim/commit/0ab55d62012c1fb38c4b540a4233421820a59389","text":"Problem: Insufficient test coverage for Python. Solution: Add more test cases. (Yegappan Lakshmanan, closes #6415)","thumb_url":"https://avatars0.githubusercontent.com/u/11618545?s=400&v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/0ab55d62012c1fb38c4b540a4233421820a59389","original_url":"https://github.com/vim/vim/commit/0ab55d62012c1fb38c4b540a4233421820a59389"}],"edited":{"user":"BPV6T0C1J","ts":"1594149495.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"<https://github.com/vim/vim/commit/fe465a01cfbbbae5d870d6108e0ad0947f03b0c4|patch 8.2.1152: Vim9: function reference is missing script prefix>\npatch 8.2.1152: Vim9: function reference is missing script prefix\n\nProblem:    Vim9: function reference is missing script prefix.\nSolution:   Use the actual function name instead of the name searched for in\n            the script context. (closes #6412)","ts":"1594155490.148100","attachments":[{"fallback":"GitHub: patch 8.2.1152: Vim9: function reference is missing script prefix · vim/vim@fe465a0","id":1,"title":"patch 8.2.1152: Vim9: function reference is missing script prefix · vim/vim@fe465a0","title_link":"https://github.com/vim/vim/commit/fe465a01cfbbbae5d870d6108e0ad0947f03b0c4","text":"Problem: Vim9: function reference is missing script prefix. Solution: Use the actual function name instead of the name searched for in the script context. (closes #6412)","thumb_url":"https://avatars0.githubusercontent.com/u/11618545?s=400&v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/fe465a01cfbbbae5d870d6108e0ad0947f03b0c4","original_url":"https://github.com/vim/vim/commit/fe465a01cfbbbae5d870d6108e0ad0947f03b0c4"}],"edited":{"user":"BPV6T0C1J","ts":"1594155490.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"<https://github.com/vim/vim/commit/bed36b939a4c66f41d1f24e32cfa521b10f22b82|patch 8.2.1153: Vim9: script test fails on some systems>\npatch 8.2.1153: Vim9: script test fails on some systems\n\nProblem:    Vim9: script test fails on some systems.\nSolution:   Return proper value from Compare().","ts":"1594157895.148300","attachments":[{"fallback":"GitHub: patch 8.2.1153: Vim9: script test fails on some systems · vim/vim@bed36b9","id":1,"title":"patch 8.2.1153: Vim9: script test fails on some systems · vim/vim@bed36b9","title_link":"https://github.com/vim/vim/commit/bed36b939a4c66f41d1f24e32cfa521b10f22b82","text":"Problem: Vim9: script test fails on some systems. Solution: Return proper value from Compare().","thumb_url":"https://avatars0.githubusercontent.com/u/11618545?s=400&v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/bed36b939a4c66f41d1f24e32cfa521b10f22b82","original_url":"https://github.com/vim/vim/commit/bed36b939a4c66f41d1f24e32cfa521b10f22b82"}],"edited":{"user":"BPV6T0C1J","ts":"1594157895.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null}]
