[{"type":"message","text":"\u003chttps://github.com/vim/vim/commit/6bfc475f717aa0412d13163d47ff6210fa611fb5|patch 8.2.2541: popup_create() does not allow boolean for \"cursorline\"\u003e\npatch 8.2.2541: popup_create() does not allow boolean for \"cursorline\"\n\nProblem:    Popup_create() does not allow boolean for \"cursorline\".\nSolution:   Use dict_get_bool(). (issue #7869)","ts":"1613945879.001900","attachments":[{"fallback":"GitHub: patch 8.2.2541: popup_create() does not allow boolean for \"cursorline\" · vim/vim@6bfc475","id":1,"title":"patch 8.2.2541: popup_create() does not allow boolean for \"cursorline\" · vim/vim@6bfc475","title_link":"https://github.com/vim/vim/commit/6bfc475f717aa0412d13163d47ff6210fa611fb5","text":"Problem: Popup_create() does not allow boolean for \"cursorline\". Solution: Use dict_get_bool(). (issue #7869)","thumb_url":"https://avatars.githubusercontent.com/u/11618545?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/6bfc475f717aa0412d13163d47ff6210fa611fb5","original_url":"https://github.com/vim/vim/commit/6bfc475f717aa0412d13163d47ff6210fa611fb5"}],"edited":{"user":"BPV6T0C1J","ts":"1613945879.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"\u003chttps://github.com/vim/vim/commit/b4893b84507570f24af32597716ffb67fb0ef24e|patch 8.2.2540: Vim9: no error for using script var name for argument\u003e\npatch 8.2.2540: Vim9: no error for using script var name for argument\n\nProblem:    Vim9: no error for using script var name for argument.\nSolution:   Check for this error. (closes #7868)","ts":"1613943482.001700","attachments":[{"fallback":"GitHub: patch 8.2.2540: Vim9: no error for using script var name for argument · vim/vim@b4893b8","id":1,"title":"patch 8.2.2540: Vim9: no error for using script var name for argument · vim/vim@b4893b8","title_link":"https://github.com/vim/vim/commit/b4893b84507570f24af32597716ffb67fb0ef24e","text":"Problem: Vim9: no error for using script var name for argument. Solution: Check for this error. (closes #7868)","thumb_url":"https://avatars.githubusercontent.com/u/11618545?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/b4893b84507570f24af32597716ffb67fb0ef24e","original_url":"https://github.com/vim/vim/commit/b4893b84507570f24af32597716ffb67fb0ef24e"}],"edited":{"user":"BPV6T0C1J","ts":"1613943484.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"\u003chttps://github.com/vim/vim/commit/7e82c5f338efe5661951675565f27f6512901a6e|patch 8.2.2539: Vim9: return from finally block causes a hang\u003e\npatch 8.2.2539: Vim9: return from finally block causes a hang\n\nProblem:    Vim9: return from finally block causes a hang.\nSolution:   Store both the finally and endtry indexes. (closes #7885)","ts":"1613939887.001500","attachments":[{"fallback":"GitHub: patch 8.2.2539: Vim9: return from finally block causes a hang · vim/vim@7e82c5f","id":1,"title":"patch 8.2.2539: Vim9: return from finally block causes a hang · vim/vim@7e82c5f","title_link":"https://github.com/vim/vim/commit/7e82c5f338efe5661951675565f27f6512901a6e","text":"Problem: Vim9: return from finally block causes a hang. Solution: Store both the finally and endtry indexes. (closes #7885)","thumb_url":"https://avatars.githubusercontent.com/u/11618545?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/7e82c5f338efe5661951675565f27f6512901a6e","original_url":"https://github.com/vim/vim/commit/7e82c5f338efe5661951675565f27f6512901a6e"}],"edited":{"user":"BPV6T0C1J","ts":"1613939887.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"\u003chttps://github.com/vim/vim/commit/21578271bb717f7ab7b8728e9efa54c3b60ee7e4|patch 8.2.2538: crash when using Python list iterator\u003e\npatch 8.2.2538: crash when using Python list iterator\n\nProblem:    Crash when using Python list iterator.\nSolution:   Increment the list reference count. (closes #7886)","ts":"1613931479.001300","attachments":[{"fallback":"GitHub: patch 8.2.2538: crash when using Python list iterator · vim/vim@2157827","id":1,"title":"patch 8.2.2538: crash when using Python list iterator · vim/vim@2157827","title_link":"https://github.com/vim/vim/commit/21578271bb717f7ab7b8728e9efa54c3b60ee7e4","text":"Problem: Crash when using Python list iterator. Solution: Increment the list reference count. (closes #7886)","thumb_url":"https://avatars.githubusercontent.com/u/11618545?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/21578271bb717f7ab7b8728e9efa54c3b60ee7e4","original_url":"https://github.com/vim/vim/commit/21578271bb717f7ab7b8728e9efa54c3b60ee7e4"}],"edited":{"user":"BPV6T0C1J","ts":"1613931480.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"\u003chttps://github.com/vim/vim/commit/027c4ab4d2e3ff031b98e0fb648f5acbea180293|patch 8.2.2537: Vim9: crash when map() fails\u003e\npatch 8.2.2537: Vim9: crash when map() fails\n\nProblem:    Vim9: crash when map() fails.\nSolution:   Clear typval before using it. (closes #7884)","ts":"1613921880.001100","attachments":[{"fallback":"GitHub: patch 8.2.2537: Vim9: crash when map() fails · vim/vim@027c4ab","id":1,"title":"patch 8.2.2537: Vim9: crash when map() fails · vim/vim@027c4ab","title_link":"https://github.com/vim/vim/commit/027c4ab4d2e3ff031b98e0fb648f5acbea180293","text":"Problem: Vim9: crash when map() fails. Solution: Clear typval before using it. (closes #7884)","thumb_url":"https://avatars.githubusercontent.com/u/11618545?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/027c4ab4d2e3ff031b98e0fb648f5acbea180293","original_url":"https://github.com/vim/vim/commit/027c4ab4d2e3ff031b98e0fb648f5acbea180293"}],"edited":{"user":"BPV6T0C1J","ts":"1613921881.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null}]
