[{"type":"message","text":"\u003chttps://github.com/vim/vim/commit/c150c09ec4f97636c6339f5687fdaa9f665095d2|patch 8.2.2506: Vim9: :continue does not work correctly in a :try block\u003e\npatch 8.2.2506: Vim9: :continue does not work correctly in a :try block\n\nProblem:    Vim9: :continue does not work correctly in a :try block\nSolution:   Add the TRYCLEANUP instruction. (closes #7827)","ts":"1613225888.027400","attachments":[{"fallback":"GitHub: patch 8.2.2506: Vim9: :continue does not work correctly in a :try block · vim/vim@c150c09","id":1,"title":"patch 8.2.2506: Vim9: :continue does not work correctly in a :try block · vim/vim@c150c09","title_link":"https://github.com/vim/vim/commit/c150c09ec4f97636c6339f5687fdaa9f665095d2","text":"Problem: Vim9: :continue does not work correctly in a :try block Solution: Add the TRYCLEANUP instruction. (closes #7827)","thumb_url":"https://avatars.githubusercontent.com/u/11618545?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/c150c09ec4f97636c6339f5687fdaa9f665095d2","original_url":"https://github.com/vim/vim/commit/c150c09ec4f97636c6339f5687fdaa9f665095d2"}],"edited":{"user":"BPV6T0C1J","ts":"1613225889.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"\u003chttps://github.com/vim/vim/commit/31842cd0772b557eb9584a13740430db29de8a51|patch 8.2.2505: Vim9: crash after defining function with invalid retu…\u003e\npatch 8.2.2505: Vim9: crash after defining function with invalid return type\n\nProblem:    Vim9: crash after defining function with invalid return type.\nSolution:   Clear function growarrays.  Fix memory leak.","ts":"1613164695.027200","attachments":[{"fallback":"GitHub: patch 8.2.2505: Vim9: crash after defining function with invalid retu… · vim/vim@31842cd","id":1,"title":"patch 8.2.2505: Vim9: crash after defining function with invalid retu… · vim/vim@31842cd","title_link":"https://github.com/vim/vim/commit/31842cd0772b557eb9584a13740430db29de8a51","text":"…rn type Problem: Vim9: crash after defining function with invalid return type. Solution: Clear function growarrays. Fix memory leak.","thumb_url":"https://avatars.githubusercontent.com/u/11618545?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/31842cd0772b557eb9584a13740430db29de8a51","original_url":"https://github.com/vim/vim/commit/31842cd0772b557eb9584a13740430db29de8a51"}],"edited":{"user":"BPV6T0C1J","ts":"1613164696.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"\u003chttps://github.com/vim/vim/commit/44ec21c467ddf481b422c787324ea08f375f6942|patch 8.2.2504: Vim9: crash when using an argument from a closure\u003e\npatch 8.2.2504: Vim9: crash when using an argument from a closure\n\nProblem:    Vim9: crash when using an argument from a closure.\nSolution:   Check if gen_load_outer is NULL. (closes #7821)","ts":"1613163494.026900","attachments":[{"fallback":"GitHub: patch 8.2.2504: Vim9: crash when using an argument from a closure · vim/vim@44ec21c","id":1,"title":"patch 8.2.2504: Vim9: crash when using an argument from a closure · vim/vim@44ec21c","title_link":"https://github.com/vim/vim/commit/44ec21c467ddf481b422c787324ea08f375f6942","text":"Problem: Vim9: crash when using an argument from a closure. Solution: Check if gen_load_outer is NULL. (closes #7821)","thumb_url":"https://avatars.githubusercontent.com/u/11618545?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/44ec21c467ddf481b422c787324ea08f375f6942","original_url":"https://github.com/vim/vim/commit/44ec21c467ddf481b422c787324ea08f375f6942"}],"edited":{"user":"BPV6T0C1J","ts":"1613163495.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"\u003chttps://github.com/vim/vim/commit/d9d7789b6fe5f2b4074375ee9f1c0bad3e4d3cfe|patch 8.2.2503: Vim9: a caught error may leave something on the stack\u003e\npatch 8.2.2503: Vim9: a caught error may leave something on the stack\n\nProblem:    Vim9: a caught error may leave something on the stack.\nSolution:   Drop items from the stack if needed. (closes #7826)","ts":"1613162286.026700","attachments":[{"fallback":"GitHub: patch 8.2.2503: Vim9: a caught error may leave something on the stack · vim/vim@d9d7789","id":1,"title":"patch 8.2.2503: Vim9: a caught error may leave something on the stack · vim/vim@d9d7789","title_link":"https://github.com/vim/vim/commit/d9d7789b6fe5f2b4074375ee9f1c0bad3e4d3cfe","text":"Problem: Vim9: a caught error may leave something on the stack. Solution: Drop items from the stack if needed. (closes #7826)","thumb_url":"https://avatars.githubusercontent.com/u/11618545?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/d9d7789b6fe5f2b4074375ee9f1c0bad3e4d3cfe","original_url":"https://github.com/vim/vim/commit/d9d7789b6fe5f2b4074375ee9f1c0bad3e4d3cfe"}],"edited":{"user":"BPV6T0C1J","ts":"1613162286.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"\u003chttps://github.com/vim/vim/commit/ca753ec862f8191f1fc5ed161753704a488ed08d|patch 8.2.2502: a few github actions are failing\u003e\npatch 8.2.2502: a few github actions are failing\n\nProblem:    A few github actions are failing.\nSolution:   Install setuptools-rust. (closes #7823)","ts":"1613156289.026500","attachments":[{"fallback":"GitHub: patch 8.2.2502: a few github actions are failing · vim/vim@ca753ec","id":1,"title":"patch 8.2.2502: a few github actions are failing · vim/vim@ca753ec","title_link":"https://github.com/vim/vim/commit/ca753ec862f8191f1fc5ed161753704a488ed08d","text":"Problem: A few github actions are failing. Solution: Install setuptools-rust. (closes #7823)","thumb_url":"https://avatars.githubusercontent.com/u/11618545?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/ca753ec862f8191f1fc5ed161753704a488ed08d","original_url":"https://github.com/vim/vim/commit/ca753ec862f8191f1fc5ed161753704a488ed08d"}],"edited":{"user":"BPV6T0C1J","ts":"1613156289.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null}]
