[{"type":"message","user":"U0143MAEY7K","text":"<@U0143MAEY7K> has joined the channel","ts":"1589559063.418400","subtype":"channel_join","replace_original":false,"delete_original":false,"blocks":null},{"type":"message","user":"U013Y44N204","text":"<@U013Y44N204> has joined the channel","ts":"1589585564.418700","subtype":"channel_join","replace_original":false,"delete_original":false,"blocks":null},{"type":"message","user":"U0144LSBYCR","text":"<@U0144LSBYCR> has joined the channel","ts":"1589597677.419000","subtype":"channel_join","replace_original":false,"delete_original":false,"blocks":null},{"client_msg_id":"73df6a60-e6a4-425b-bc20-077a637acc49","type":"message","user":"U013QL1RAPN","text":"前者の設定（＃で囲む）はこのように一行追加いたしましたら、できるようになりました。","ts":"1589600188.419200","thread_ts":"1589359542.369600","edited":{"user":"U013QL1RAPN","ts":"1589604279.000000"},"parent_user_id":"U013QL1RAPN","files":[{"id":"F013QM7CAH3","created":1589600178,"timestamp":1589600178,"name":"無題","title":"無題","mimetype":"text/plain","image_exif_rotation":0,"filetype":"text","pretty_type":"Plain Text","user":"U013QL1RAPN","mode":"snippet","editable":true,"is_external":false,"external_type":"","size":169,"url":"","url_download":"","url_private":"https://files.slack.com/files-pri/T03C4RC8V-F013QM7CAH3/______","url_private_download":"https://files.slack.com/files-pri/T03C4RC8V-F013QM7CAH3/download/______","original_h":0,"original_w":0,"thumb_64":"","thumb_80":"","thumb_160":"","thumb_360":"","thumb_360_gif":"","thumb_360_w":0,"thumb_360_h":0,"thumb_480":"","thumb_480_w":0,"thumb_480_h":0,"thumb_720":"","thumb_720_w":0,"thumb_720_h":0,"thumb_960":"","thumb_960_w":0,"thumb_960_h":0,"thumb_1024":"","thumb_1024_w":0,"thumb_1024_h":0,"permalink":"https://vim-jp.slack.com/files/U013QL1RAPN/F013QM7CAH3/______","permalink_public":"https://slack-files.com/T03C4RC8V-F013QM7CAH3-42edc4c276","edit_link":"https://vim-jp.slack.com/files/U013QL1RAPN/F013QM7CAH3/______/edit","preview":"","preview_highlight":"","lines":0,"lines_more":0,"is_public":true,"public_url_shared":false,"channels":null,"groups":null,"ims":null,"initial_comment":{},"comments_count":0,"num_stars":0,"is_starred":false,"shares":{"public":null,"private":null},"display_as_bot":false,"has_rich_preview":false,"username":""}],"upload":true,"replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"SihM2"}]},{"type":"message","user":"U013KAVBX8E","text":"<@U013KAVBX8E> has joined the channel","ts":"1589600377.419700","subtype":"channel_join","replace_original":false,"delete_original":false,"blocks":null},{"type":"message","user":"U013S3AAB3L","text":"<@U013S3AAB3L> has joined the channel","ts":"1589601908.420000","subtype":"channel_join","replace_original":false,"delete_original":false,"blocks":null},{"type":"message","user":"U013QN4DTQV","text":"<@U013QN4DTQV> has joined the channel","ts":"1589604924.420400","subtype":"channel_join","replace_original":false,"delete_original":false,"blocks":null},{"type":"message","user":"U013BCAT63Z","text":"<@U013BCAT63Z> has joined the channel","ts":"1589609577.420700","subtype":"channel_join","replace_original":false,"delete_original":false,"blocks":null},{"type":"message","user":"U013SC1LJG3","text":"<@U013SC1LJG3> has joined the channel","ts":"1589615826.421000","subtype":"channel_join","replace_original":false,"delete_original":false,"blocks":null},{"type":"message","user":"U013BFWKH71","text":"<@U013BFWKH71> has joined the channel","ts":"1589626789.421300","subtype":"channel_join","replace_original":false,"delete_original":false,"blocks":null},{"client_msg_id":"f82e9126-990e-4726-bf2a-eec39a449290","type":"message","user":"UP6PA1UBE","text":"ローカルの環境なんですが、Python 3.8.1 から 3.8.2 にアップグレードしたら `print(sys.path)` がおかしくなって vim で `:py3 1` すると落ちるようになったんですよね。\n(python.exe から見ると正常でなんでやってなった)\n```Python path configuration:\n  PYTHONHOME = (not set)\n  PYTHONPATH = (not set)\n  program name = 'python'\n  isolated = 0\n  environment = 1\n  user site = 1\n  import site = 1\n  sys._base_executable = 'C:\\tools\\vim\\vim82\\\\vim.exe'\n  sys.base_prefix = 'C:\\\\Users\\\\NAME\\\\.pyenv\\\\pyenv-win\\\\versions\\\\3.8.2-amd64'\n  sys.base_exec_prefix = 'C:\\\\Users\\\\NAME\\\\.pyenv\\\\pyenv-win\\\\versions\\\\3.8.2-amd64'\n  sys.executable = 'C:\\tools\\vim\\vim82\\\\vim.exe'\n  sys.prefix = 'C:\\\\Users\\\\NAME\\\\.pyenv\\\\pyenv-win\\\\versions\\\\3.8.2-amd64'\n  sys.exec_prefix = 'C:\\\\Users\\\\NAME\\\\.pyenv\\\\pyenv-win\\\\versions\\\\3.8.2-amd64'\n  sys.path = [\n    'C:\\\\Users\\\\NAME\\\\.pyenv\\\\pyenv-win\\\\versions\\\\3.8.2-amd64\\\\python38.zip',\n    'C:\\\\Users\\\\NAME\\\\.pyenv\\\\pyenv-win\\\\versions\\\\3.8.1-amd64\\\\DLLs',\n    'C:\\\\Users\\\\NAME\\\\.pyenv\\\\pyenv-win\\\\versions\\\\3.8.1-amd64\\\\lib',\n    'C:\\\\tools\\\\vim\\\\vim82',\n  ]\nFatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding\nPython runtime state: core initialized\nModuleNotFoundError: No module named 'encodings'\n\nCurrent thread 0x00008a64 (most recent call first):\n&lt;no Python frame&gt;```","ts":"1589640317.425900","edited":{"user":"UP6PA1UBE","ts":"1589640400.000000"},"team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"ykQ"}],"source_team":"T03C4RC8V","user_team":"T03C4RC8V"}]
