[{"client_msg_id":"e6434296-3628-465c-b239-7cfc61004912","type":"message","user":"U06BRP8VD","text":"MSVC + 8.1.0005 + python 2 だと落ちないのはOKなのかな?","ts":"1552057269.036500","edited":{"user":"U06BRP8VD","ts":"1552057289.000000"},"team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":null,"source_team":"T03C4RC8V","user_team":"T03C4RC8V"},{"client_msg_id":"335deee4-7e27-42d6-97e0-ef6438cadf96","type":"message","user":"U06BRP8VD","text":"`echo 1 | vim -c \"py print(1)\" -` 実行したのはコウだけど。","ts":"1552057304.037100","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":null,"source_team":"T03C4RC8V","user_team":"T03C4RC8V"},{"client_msg_id":"acd4a791-d74a-438f-9e7f-f0ccd27967b0","type":"message","user":"U03C6TEAZ","text":"あざます。python ランタイムの話なので _MSC_VER は呼ばないみたいなことも出来ないので確認助かります。","ts":"1552084454.039100","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":null,"source_team":"T03C4RC8V","user_team":"T03C4RC8V"},{"client_msg_id":"0c443826-4b49-4e67-93fb-68332f60ca1a","type":"message","user":"UFZL441S8","text":"Win10+MSVC+8.1.0998+python3 で見ました。vim.exe は落ちません(vim画面最下行に 1 と表示されて通常起動のように見える)、gvim は Py_FatalInitError からの Py_SetLocaleFromEnv 経由で abort します。C0000409 なのでとりあえずバッファオーバーランですかね…","ts":"1552088132.042700","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":null,"source_team":"T03C4RC8V","user_team":"T03C4RC8V"},{"client_msg_id":"d51b4685-73e3-4918-8c6c-5b2205783927","type":"message","user":"UFZL441S8","text":"Win10+MSVC+8.1.0998+python2 の gvim は vim.exe と同様に「落ちません」。通常起動のように見えます。","ts":"1552088563.043700","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":null,"source_team":"T03C4RC8V","user_team":"T03C4RC8V"},{"client_msg_id":"807ff5c7-eac4-4130-be47-9162963df6ad","type":"message","user":"U6XP9LZ6V","text":"VC2015+8.1.0997+python3, vim.exe, gvim.exe どちらも落ちました。","ts":"1552095408.044800","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":null,"source_team":"T03C4RC8V","user_team":"T03C4RC8V"},{"client_msg_id":"e77cfd41-8bc1-47aa-90cd-ecda24286f35","type":"message","user":"U06BRP8VD","text":"いぜん k-takata さんに教えてもらったPythonの位置を設定する ~環境変数~ レジストリってありませんでしたっけ? それのおかげ?","ts":"1552096690.045700","edited":{"user":"U06BRP8VD","ts":"1552096706.000000"},"team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":null,"source_team":"T03C4RC8V","user_team":"T03C4RC8V"},{"client_msg_id":"504a27db-add3-4782-8370-3a3beddbf993","type":"message","user":"U6XP9LZ6V","text":"どうだろう。2.7の一部のバージョンでの対策でしたね。それなら代わりにPYTHONHOMEとか設定したら何か変わるだろうか。","ts":"1552098850.049400","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":null,"source_team":"T03C4RC8V","user_team":"T03C4RC8V"},{"client_msg_id":"a7b31e9f-07e0-4acd-a7cc-d63f48fb9fae","type":"message","user":"U6XP9LZ6V","text":"mattnさんのパッチはまだ試してない。","ts":"1552098989.050100","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":null,"source_team":"T03C4RC8V","user_team":"T03C4RC8V"},{"client_msg_id":"6dc68e5c-1353-48ed-b8ee-07c8f5241c87","type":"message","user":"UFZL441S8","text":"うちは VC2017 でした。あれ？前述パッチを入れた結果 vim.exe が落ちなくて gvim が落ちたという意味合いです。","ts":"1552100373.052200","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":null,"source_team":"T03C4RC8V","user_team":"T03C4RC8V"}]
