[{"client_msg_id":"996787b5-f3a8-4864-ae7c-bc8f19b3a1c5","type":"message","user":"U6XP9LZ6V","text":"結局 python 側は `GetConsoleMode()` , `GetNumberOfConsoleInputEvents()`, `fstat()` の組み合わせで stdin が有効かどうかチェックしていたので、vim 側でも同じ条件でチェックして stdin が無効なら NUL を `freopen()` するようにしました。","ts":"1602227409.270800","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"Bxpj"}]},{"client_msg_id":"11014975-0d4c-4db6-98d2-6fa104bd2d9e","type":"message","user":"U6XP9LZ6V","text":"gvim と vim、`-c \"py3 print(1)\"` と `--cmd \"py3 print(1)\"`、stdin をリダイレクトする・しないの組み合わせで、python が何をチェックして abort しているのかを調べるのは結構苦労しましたｗ","ts":"1602227181.268200","team":"T03C4RC8V","reactions":[{"name":"yokuyasundekudasai","count":2,"users":["U03C6TEAZ","UAZ33BKV2"]}],"replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"/NQBe"}]},{"client_msg_id":"d422daaf-39de-4d45-8f1a-fe381fb5262a","type":"message","user":"U03C6TEAZ","text":"ここまでしないと原因わからないのしんどいなぁ。","ts":"1602227175.268100","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"mP8"}]},{"client_msg_id":"665aad20-2840-4040-991d-913fb948a5ac","type":"message","user":"UAZ33BKV2","text":"おつかれさまです....","ts":"1602226738.265600","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"i0zu"}]},{"client_msg_id":"44b2929c-6d3e-47af-afde-51ca369b1348","type":"message","user":"U6XP9LZ6V","text":"結局 python の dll を自分でビルドして、デバッガ上で動かして python が abort する条件を見つけ出した。","ts":"1602226287.265400","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"1+9x"}]},{"client_msg_id":"72df6f46-04f7-4380-a1ba-db780b5604ce","type":"message","user":"U6XP9LZ6V","text":"パッチを更新。グローバルなフラグは不要になった。\n\u003chttps://osdn.net/users/k_takata/pf/vim-ktakata-mq/scm/blobs/fcfa38920bc03efd37a971755ca155d9844df336/fix-python3-stdin.patch\u003e","ts":"1602226043.264000","attachments":[{"fallback":"File Details: /fix-python3-stdin.patch (fcfa38920bc03efd37a971755ca155d9844df336) - vim-ktakat...","id":1,"title":"File Details: /fix-python3-stdin.patch (fcfa38920bc03efd37a971755ca155d9844df336) - vim-ktakat...","title_link":"https://osdn.net/users/k_takata/pf/vim-ktakata-mq/scm/blobs/fcfa38920bc03efd37a971755ca155d9844df336/fix-python3-stdin.patch","text":"File Details: /fix-python3-stdin.patch (fcfa38920bc03efd37a971755ca155d9844df336) - vim-ktakata-mq (hg) #osdn","thumb_url":"https://static.osdn.net/OSDN_icon_125x125.png","blocks":null,"service_name":"osdn.net","service_icon":"https://osdn.net/favicon.ico","thumb_width":125,"thumb_height":125,"from_url":"https://osdn.net/users/k_takata/pf/vim-ktakata-mq/scm/blobs/fcfa38920bc03efd37a971755ca155d9844df336/fix-python3-stdin.patch","original_url":"https://osdn.net/users/k_takata/pf/vim-ktakata-mq/scm/blobs/fcfa38920bc03efd37a971755ca155d9844df336/fix-python3-stdin.patch"}],"team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"4AL"}]},{"client_msg_id":"1398e566-69b8-4f7a-9acc-c80e336a5d22","type":"message","user":"U6XP9LZ6V","text":"あー、分かった。python 側では `GetNumberOfConsoleInputEvents()` で stdin のハンドルがコンソール入力に使えるかチェックしてる。fd 2 をコピーしたハンドルだと書き込み専用だから、ここでエラーになってる。\n\u003chttps://github.com/python/cpython/blob/4e0ce820586e93cfcefb16c2a3df8eaefc54cbca/Modules/_io/winconsoleio.c#L58\u003e","ts":"1602205809.263300","attachments":[{"fallback":"GitHub: python/cpython","id":1,"title":"python/cpython","title_link":"https://github.com/python/cpython/blob/4e0ce820586e93cfcefb16c2a3df8eaefc54cbca/Modules/_io/winconsoleio.c#L58","text":"The Python programming language. Contribute to python/cpython development by creating an account on GitHub.","thumb_url":"https://avatars2.githubusercontent.com/u/1525981?s=400\u0026v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":400,"thumb_height":400,"from_url":"https://github.com/python/cpython/blob/4e0ce820586e93cfcefb16c2a3df8eaefc54cbca/Modules/_io/winconsoleio.c#L58","original_url":"https://github.com/python/cpython/blob/4e0ce820586e93cfcefb16c2a3df8eaefc54cbca/Modules/_io/winconsoleio.c#L58"}],"team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"WRef"}]},{"client_msg_id":"b46ca876-b70f-4f95-af96-c1388fa8a40f","type":"message","user":"U6XP9LZ6V","text":"でも、再利用されているなら何で python 側でエラーになるんだ？","ts":"1602205026.261300","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"SgvHD"}]},{"client_msg_id":"351db324-eaa4-41ef-ba73-b8eb45f1a3b5","type":"message","user":"U6XP9LZ6V","text":"やっぱり fd 0 が再利用されて、OS のハンドルも再利用されていた。","ts":"1602204990.260600","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"CMr"}]},{"client_msg_id":"bea57c9a-df80-421b-9b9a-3783847bc173","type":"message","user":"U6XP9LZ6V","text":"あー、fd 0 をクローズされたのが検出できないのは、再利用されているからか？\n`close(0)` を実行した後に `dup(2)` を実行しているから、fd 2 が fd 0 にコピーされているのかも。後で調べるか","ts":"1602200594.259700","team":"T03C4RC8V","replace_original":false,"delete_original":false,"blocks":[{"type":"rich_text","block_id":"Hf73n"}]}]
